name: utm_x_change
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_splash_screen: ^3.0.1 
  font_awesome_flutter: ^8.8.1
  pie_chart: ^3.1.1
  badges: ^1.1.1
  carousel_slider: ^2.0.0
  timeline: ^0.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/flare_files/splash.flr
   - assets/customIcons/icon_red.png
   - assets/customIcons/icon_transparent.png
   - assets/images/avator.png
   - assets/images/avator.jpg
   - assets/images/headShape.png
   - assets/images/underConstruction.png
   - assets/images/logout.png
   - assets/images/shape.png
   - assets/images/shopping_home.png
   - assets/images/dosanddonts.png
   - assets/images/like.png
   - assets/images/dislike.png
   - assets/images/livingCost.png
   - assets/images/legoland.png
   - assets/images/puteri_harbour.jpg
   - assets/images/jpo.jpg
   - assets/images/hotels.png
   - assets/images/R&F TANJUNG PUTERI.jpg
   - assets/images/places.png
   - assets/images/checkListHome.png
   - assets/images/documnets.png
   - assets/images/tips.png
   - assets/images/personal.png
   - assets/images/personal_9.png
   - assets/images/friends.png
   - assets/images/notice.jpg
   - assets/images/malaysia.png
   - assets/images/multinational.jpg
   - assets/images/utm.jpg
   - assets/images/king.jpg
   - assets/images/money.jpg
   - assets/images/utmNature.jpg
   - assets/images/utmMosque.jpg
   - assets/images/askQuestion.png
   - assets/images/guideline.png
   - assets/images/travel.png
   - assets/images/plane.png
   - assets/images/train.png
   - assets/images/train_mod.png
   - assets/images/bus.png
   - assets/images/bus_mod.png
   - assets/images/utmbg.png
   - assets/images/air_asia.png
   - assets/images/firefly.png
   - assets/images/malaysia_airlines.png
   - assets/images/arrive.png
   - assets/images/malindo_airlines.png
   - assets/images/done.png
   - assets/images/step1.png
   - assets/images/step2.png
   - assets/images/step3.png
   - assets/images/step4.png
   - assets/images/step5.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Overlock
      fonts:
        - asset: assets/fonts/Overlock-Regular.ttf
        - asset: assets/fonts/Overlock-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
